version = 0.1
[default.deploy.parameters]
stack_name = "water-district-billing-api-stack"
resolve_s3 = true
s3_prefix = "water-district-billing-api-stack"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
