AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  water-district-billing-api

Globals:
  Function:
    Environment:
      Variables:
        ENV: !Ref ENV
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    Timeout: 30
    Runtime: nodejs20.x
    Architectures:
      - arm64
    Layers:
      - arn:aws:lambda:ap-southeast-1:975050335698:layer:water-district-deps:3
      - arn:aws:lambda:ap-southeast-1:044395824272:layer:AWS-Parameters-and-Secrets-Lambda-Extension-Arm64:11

Parameters:
  ENV:
    Type: String

Resources:
  WaterDistrictBillingApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      ApiKeySourceType: HEADER
      Auth:
        ApiKeyRequired: true
        UsagePlan:
          CreateUsagePlan: SHARED

  GetBillingApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .dist/get/
      Handler: get.handler
      Events:
        GetBilling:
          Type: Api
          Properties:
            Path: /billings
            Method: get
            RestApiId: !Ref WaterDistrictBillingApi
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:ap-southeast-1:975050335698:parameter/water-district-db/*

  GetBillingByIdApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .dist/getById/
      Handler: getById.handler
      Events:
        GetBilling:
          Type: Api
          Properties:
            Path: /billings/{id}
            Method: get
            RestApiId: !Ref WaterDistrictBillingApi
            Auth:
              ApiKeyRequired: true
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:ap-southeast-1:975050335698:parameter/water-district-db/*

  DeleteBillingByIdApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .dist/deleteById/
      Handler: deleteById.handler
      Events:
        DeleteBilling:
          Type: Api
          Properties:
            Path: /billings/{id}
            Method: delete
            RestApiId: !Ref WaterDistrictBillingApi
            Auth:
              ApiKeyRequired: true
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:ap-southeast-1:975050335698:parameter/water-district-db/*

  PatchBillingByIdApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .dist/patchById/
      Handler: patchById.handler
      Events:
        PatchBilling:
          Type: Api
          Properties:
            Path: /billings/{id}
            Method: patch
            RestApiId: !Ref WaterDistrictBillingApi
            Auth:
              ApiKeyRequired: true
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:ap-southeast-1:975050335698:parameter/water-district-db/*
        
  CreateBillingApi:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .dist/post/
      Handler: post.handler
      Events:
        CreateBilling:
          Type: Api
          Properties:
            Path: /billings
            Method: post
            RestApiId: !Ref WaterDistrictBillingApi
            Auth:
              ApiKeyRequired: true
      Policies:
      - Statement:
        - Sid: SSMGetParameterPolicy
          Effect: Allow
          Action:
            - ssm:GetParameter
          Resource: arn:aws:ssm:ap-southeast-1:975050335698:parameter/water-district-db/*
